//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTicketWearable.Resources {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTicketWearable.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyTicketWearable.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MyTicketWearable.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string GridLayoutPageBottomText
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageBottomText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Bottom value.
        /// </summary>
        public static string GridLayoutPageBottomValue
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageBottomValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string GridLayoutPageLeftText
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageLeftText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left unit.
        /// </summary>
        public static string GridLayoutPageLeftUnit
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageLeftUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Left value.
        /// </summary>
        public static string GridLayoutPageLeftValue
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageLeftValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string GridLayoutPageRightText
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageRightText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right unit.
        /// </summary>
        public static string GridLayoutPageRightUnit
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageRightUnit", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Right value.
        /// </summary>
        public static string GridLayoutPageRightValue
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageRightValue", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string GridLayoutPageTopText
        {
            get
            {
                return ResourceManager.GetString("GridLayoutPageTopText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to GridLayout.
        /// </summary>
        public static string GridLayoutPageTitle {
            get {
                return ResourceManager.GetString("GridLayoutPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to TextList.
        /// </summary>
        public static string TextListPageTitle {
            get {
                return ResourceManager.GetString("TextListPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Toast will disappear in {0} seconds.
        /// </summary>
        public static string ToastPageToastMessage {
            get {
                return ResourceManager.GetString("ToastPageToastMessage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Toast.
        /// </summary>
        public static string ToastPageTitle {
            get {
                return ResourceManager.GetString("ToastPageTitle", resourceCulture);
            }
        }
    
            /// <summary>
            ///   Looks up a localized string similar to OK.
            /// </summary>
            public static string EntryPageBottomButtonText {
                get {
                    return ResourceManager.GetString("EntryPageBottomButtonText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Comment.
            /// </summary>
            public static string Comment {
                get {
                    return ResourceManager.GetString("Comment", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Password.
            /// </summary>
            public static string Password {
                get {
                    return ResourceManager.GetString("Password", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Phone.
            /// </summary>
            public static string PhoneNumber {
                get {
                    return ResourceManager.GetString("PhoneNumber", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string EntryPageTitle {
            get {
                return ResourceManager.GetString("EntryPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ScrollView.
        /// </summary>
        public static string ScrollViewPageTitle {
            get {
                return ResourceManager.GetString("ScrollViewPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Vibration is not supported.
        /// </summary>
        public static string ExceptionVibrationServiceNotSupported {
            get {
                return ResourceManager.GetString("ExceptionVibrationServiceNotSupported", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Predefined vibration is not supported.
        /// </summary>
        public static string ExceptionVibrationServicePredefinedNotSupported {
            get {
                return ResourceManager.GetString("ExceptionVibrationServicePredefinedNotSupported", resourceCulture);
            }
        }
    }
}
